Update for Needle
New algorithm, better memory management, and less dependencies

diff --git a/needle b/needle
--- a/needle
+++ b/needle
@@ -1,7 +1,9 @@
-#!/bin/bash
-
-#code injector
-
+#!/usr/bin/env bash
+# -*- coding: utf-8 -*-
+# Version: v.2
+# Console-Needle Branch
+# GitHub: https://github.com/OakAtsume/needle/tree/Console-needle
+# Creator: Oak atsume, Shoutout to Ceritified-Rice for fixing typo's!
 printf "
                                   █████ ████
                                  ░░███ ░░███
@@ -12,86 +14,117 @@ printf "
  ████ █████░░██████ ░░██████ ░░████████ █████░░██████
 ░░░░ ░░░░░  ░░░░░░   ░░░░░░   ░░░░░░░░ ░░░░░  ░░░░░░\n"
 
-
-
-
-#Varible name is nice
-file_with_code="$2"
-Target="$3"
-
-
-
-if [[ -z $1 ]];
-then
-	echo "Usage:"
-	echo "
-  needle {option}
-  needle replace \"1\" \"2\" {file}
-  needle inject 1.txt 2.txt {option}
-  needle inject 1.txt 2.txt replace \"1\" \"2\" "
+if [[ -z "${1}" ]]; then
+  echo -e "Usage:\nSyntax: needle {Options},\nOptions: \nneedle replace : Find and replace all matches in a file\n>>> needle replace 'find-and-replace-me' 'replace-to-this' {file}\n"
+  echo -e "needle inject 'file1' 'file2' {additional-options}\n>>> needle inject 'code.txt' 'target-file.sh'"
+  echo -e ">>> needle inject 'file1' 'file2' replace 'value1' 'value2'"
+  echo -e "[New]>>> needle Console : drop to new experimental console"
+  exit 2
 fi
 
-case $1 in
-  -h|help|-help|--help|--h)
-	echo "Usage:"
-  echo "
-  needle {option}
-  needle replace \"1\" \"2\" {file}
-  needle inject 1.txt 2.txt {option}
-  needle inject 1.txt 2.txt replace \"1\" \"2\" "
+case "${1}" in
+  -h|--help|--h)
+  echo -e "Usage:\nSyntax: needle {Options},\nOptions: \nneedle replace : Find and replace all matches in a file\n>>> needle replace 'find-and-replace-me' 'replace-to-this' {file}\n"
+  echo -e "needle inject 'file1' 'file2' {additional-options}\n>>> needle inject 'code.txt' 'target-file.sh'"
+  echo -e ">>> needle inject 'file1' 'file2' replace 'value1' 'value2'"
+  echo -e "[New]>>> needle Console : drop to new experimental console"
+  exit 2
   ;;
-esac
-
-case $1 in
   replace)
-  printf "Replace\n"
-  printf '%s' "Word-1: $2\n"
-  printf '%s' "Word-2: $3\n"
-  printf '%s' "The following keyword ($2) will be Replaced with ($3) in file ($4)\n"
-  sed -i "s/$2/$3/g" "$4"
-  ;;
-esac
-
-case $1 in
-inject)
-  printf "Option 1\n"
-  printf '%s' "File-1: [$file_with_code]\n"
-  printf '%s' "File-2: [$Target]\n"
-  if [[ -f "$file_with_code" ]];
-  then
-    printf "File-1 found!\n"
+  if [[ -z  "${3}" ]]; then
+    echo "Missing Values please run the --help flag for assistance!"
+    exit 1
+  fi
+  String="${2}"
+  Replacement="${3}"
+  File="${4}"
+  if [[ ! -f "${File}" ]]; then
+    echo -e "I am unable to locate file ${File}!"
+    exit 1
+  elif [[ ! -w "${File}" || ! -r "${File}" ]]; then
+    echo -e "I am unable to write/read file ${File}"
+    exit 1
+  fi
+  echo "Maping out ${File} please wait..."
+  if readarray FileMap < "${File}"; then
+    echo -e "File Maped out to an array with ${#FileMap[@]} elements\n"
   else
-    echo "File-1 Not found!"
+    echo "Unable to Map out file!! Please report this issue!!!"
+    exit 1
+  fi
+  :> "${File}"
+  end="${#FileMap[@]}"
+  for (( a=0; a<="${end}";a++ )); do
+    #echo "${FileMap[a]//${String}/${Replacement}}
+    #:> "${File}"
+    echo "[${a}/${end}] : ${#FileMap[*]}"
+    if [[ ${FileMap[a]} =~ ${String} ]]; then
+      echo -n "${FileMap[a]//${String}/${Replacement}}" >> "${File}"
+      else
+      echo -n "${FileMap[a]}" >> "${File}"
+    fi
+    unset "FileMap[a]"
+    
+  done
+  echo "Finished Replacing matches!"
+  if unset FileMap; then
+    echo -e "[\e[38;2;255;255;0mMemory\e[m]: Clearing File's Map to save system memory! : ${#FileMap[@]}"
+  else
+    echo "[Memory]: Unable to Clear memory!!"
+    exit 1
+  fi
+  #echo "Purging file..."
+  #:> "${File}"
+  read -rt "1" <> <(:) || :
+  echo -e "\n"
+  # for a in "${NewFile[@]}"; do
+  #   echo -n "${a}" >> "${File}"
+  # done
+  # if unset NewFile; then
+  #   echo -e "[\e[38;2;255;255;0mMemory\e[m]: Clearing New Map to save system memory!"
+  # else
+  #   echo "[Memory]: Unable to Clear memory!!"
+  #   exit 1
+  # fi
+  echo "Done! [$?]"
+  exit
+  ;;
+  inject)
+  if [[ -z "${3}" ]]; then
+    echo "Missing Values please run the --help flag for assistance!"
+    exit 1
+  fi
+  CodeFile="${2}"
+  InjectionFile="${3}"
+  additional="${4}"
+  String="${5}"
+  Replacement="${6}"
+
+  if [[ ! -f "${CodeFile}" || ! -f "${InjectionFile}" ]]; then
+    echo -e "I am unable to locate file ${CodeFile}/${InjectionFile}!"
+    exit 1
+  elif [[ ! -w "${InjectionFile}" || ! -r "${CodeFile}" ]]; then
+    echo -e "I am unable to write/read file ${InjectionFile}, ${CodeFile}"
     exit 1
   fi
 
-  
-  # Nice
-  if [[ -f "$Target" ]];
-  then
-    printf "File-2 found!\n"
+  if [[ -n ${additional} ]]; then
+
+  while read -r Line; do
+    if [[ ${Line} =~ ${String} ]]; then
+    echo "${Line//${String}/${Replacement}}" >> "${InjectionFile}"
+    else
+    echo "${Line}" >> "${InjectionFile}"
+    fi
+  done <"${CodeFile}"
   else
-    echo "File-2 Not found!"
-    exit 1
+  while read -r Line; do
+    echo "${Line}" >> "${InjectionFile}"
+  done <"${CodeFile}"
   fi
-  sleep 1
-  printf "Running Injection..."
-  echo '' > "$Target"
-  cat "$file_with_code" >> "$Target"
-  echo "[*]"
-  echo "Done!"
+  echo "Done! ~OvO~"
   ;;
 esac
 
-#Varible name is nice
-case $4 in
-  replace)
-  printf "Replace\n"
-  printf '%s' "Word-1: $5\n"
-  printf '%s' "Word-2: $6\n"
-  printf '%s' "The following keyword ($5) will be Replaced with ($6) in file ($Target)\n"
-  sed -i "s/$5/$6/g" "$Target"
-  ;;
-esac
-
-#test
+#   needle inject 1.txt 2.txt {option}
+#   needle inject 1.txt 2.txt replace \"1\" \"2\" "
